name: Release

on:
  pull_request_target:
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release_job:
    uses: stefanorosanelli/github-workflows/.github/workflows/release.yml@fix/package-json
    with:
      main_branch: 'main'
      dist_branches: '["main"]'
      package_json_version: true

  docker_push:
    runs-on: 'ubuntu-latest'
    needs: release_job

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug output version
        run: |
          echo version var ${{ needs.release_job.outputs.version }}

      - name: Print message if no semantic version was created
        if: contains(needs.release_job.outputs.version, 'undefined')
        run: |
          echo Skip version file update and docker image creation

      - name: Update version key in package.json
        if: ${{ !contains(needs.release_job.outputs.version, 'undefined') }}
        run: |
          sed -i 's/"version": ".*/"version": "${{ needs.release_job.outputs.version }}",/' package.json

      - name: Log in to the Container registry
        if: ${{ !contains(needs.release_job.outputs.version, 'undefined') }}
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ !contains(needs.release_job.outputs.version, 'undefined') }}
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ needs.release_job.outputs.version }}
